// <auto-generated />
using System;
using GuessMyAge.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuessMyAge.Database.Migrations
{
    [DbContext(typeof(GuessMyAgeDbContext))]
    [Migration("20211205112820_DatabaseInitialisation")]
    partial class DatabaseInitialisation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GuessMyAge.Database.Entities.GameDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserName");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GuessMyAge.Database.Entities.PersonDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("GuessMyAge.Database.Entities.PlayerDatabaseEntity", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GuessMyAge.Database.Entities.GameDatabaseEntity", b =>
                {
                    b.HasOne("GuessMyAge.Database.Entities.PersonDatabaseEntity", "Person")
                        .WithMany("Games")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuessMyAge.Database.Entities.PlayerDatabaseEntity", "Player")
                        .WithMany("Games")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GuessMyAge.Database.Entities.PersonDatabaseEntity", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GuessMyAge.Database.Entities.PlayerDatabaseEntity", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
